INSERT INTO demo_db.public.dq_config
VALUES
('UDX','DEMO_DB','PUBLIC','UDX_ITEMS','DQ_002','ITEMNUM',NULL,NULL,0.00,'HIGH',TRUE,'DQ_TOOL',CURRENT_TIMESTAMP()),
('UDX','DEMO_DB','PUBLIC','UDX_ITEMS','DQ_001','MSDSNUM',NULL,NULL,0.20,'HIGH',TRUE,'DQ_TOOL',CURRENT_TIMESTAMP()),
('UDX','DEMO_DB','PUBLIC','UDX_ITEMS','DQ_003','MSDSNUM',800,1000,0,'HIGH',TRUE,'DQ_TOOL',CURRENT_TIMESTAMP()),
('UDX','DEMO_DB','PUBLIC','UDX_ITEMS','DQ_004','ITEMNUM',NULL,NULL,0,'HIGH',TRUE,'DQ_TOOL',CURRENT_TIMESTAMP());
